import { ErrorType } from '@app/shared/errorType';

export const errTypes = {
  FAILED_TO_CREATE_CART: 'FAILED_TO_CREATE_CART',
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_UPDATE_FAILED: 'PRODUCT_UPDATE_FAILED',
  PRODUCT_ADD_FAILED: 'PRODUCT_ADD_FAILED',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_ITEM_NOT_DELETED: 'CART_ITEM_NOT_DELETED',
  CART_NOT_DELETED: 'CART_NOT_DELETED',
} as const;

export interface CartError extends ErrorType {
  type: keyof typeof errTypes;
}
